site_name: Lilith Notes
theme: 
  name: material
  nav_style: dark
  palette:
    scheme: slate
    primary: pink
    accent: purple
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LilithsDemon
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/lucy__gardener
    - icon: fontawesome/brands/discord
      link: https://github.com/LilithsDemon

copyright: Copyright &copy; 2022 Lucy Gardener

plugins:
  - search
  - include_dir_to_nav
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog

nav:
  - Notes: 
    - Home: 'index.md'
    - Year1
  - Blog: 
    -  blog/index.md
      
