site_name: Lilith Notes
theme: 
  name: material
  logo: lilith.png
  nav_style: dark
  palette:
    scheme: slate
    primary: pink
    accent: purple
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LilithsDemon
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/lucy__gardener
    - icon: fontawesome/brands/discord
      link: https://github.com/LilithsDemon

extra_javascript:
  - JS/flowchart.js

copyright: Copyright &copy; 2022 Lucy Gardener

plugins:
  - search
  - include_dir_to_nav
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Notes: 
    - Home: 'index.md'
    - Year1
  - Assignments:
    - Assignments

repo_url: https://github.com/LilithsDemon/lilithnotes.github.io
repo_name: LilithsDemon/Lilith-Notes
